POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "a@a.cs",
    "password": "mypassword"
}

### Find user by email
GET http://localhost:3000/auth/?email=a@a.cs

### Delete user by id
DELETE http://localhost:3000/auth/3 


### Update user by id

PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "a@asddds.cs",
    "password": "mypasssword"
}


